# Generated by Django 2.2.16 on 2022-10-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221013_1802'),
        ('users', '0002_auto_20221013_1548'),
    ]

    operations = [
    ]
